# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib matsunoR, .registration = TRUE
#' @import Rcpp
NULL

#' Calculate truncated normal cumulative distribution function
#'
#' Computes the cumulative distribution function of a truncated normal
#' distribution in a numerically stable way.
#'
#' Memo: the defualt values of `a` and `b` do not work. The only solution seems to create a wrapper of this using R. 
#' Basically, we cannot set the default values to be Inf. Now, I specify R_NegInf and R_PosInf, but these are not parsed.
#' If I do not specify default values, the function is not compiled. So, this is a hacky way to make it work.
#'
#' @param x Vector of quantiles.
#' @param mean Mean of the normal distribution before truncation (default: 0).
#' @param sd Standard deviation of the normal distribution before truncation (default: 1).
#' @param a Lower truncation point.
#' @param b Upper truncation point.
#'
#' @return Vector of probabilities corresponding to the CDF evaluated at each value in x.
#' @export 
ptruncnorm_cpp <- function(x, mean = 0.0, sd = 1.0, a, b) {
    .Call(`_matsunoR_ptruncnorm_cpp`, x, mean, sd, a, b)
}

#' Simple numerical integration using trapezoidal rule
#'
#' High-performance C++ implementation using simple trapezoidal rule.
#' Fast and straightforward integration for smooth functions.
#'
#' @param f R function to integrate
#' @param lower Lower bound of integration
#' @param upper Upper bound of integration
#' @param n Number of subdivisions (default: 1000)
#'
#' @return List containing:
#' \\itemize{
#'   \\item value: The integral value
#'   \\item subdivisions: Number of subdivisions used
#' }
#' @export
integrate_cpp <- function(f, lower, upper, n = 1000L) {
    .Call(`_matsunoR_integrate_cpp`, f, lower, upper, n)
}

